### ISSUE TITLE
Statement error after upgrade on dynamic labels

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#275]
```
Uncaught exception of type 'STATEMENT_ERROR' on line 17 at position 4 : SQL compilation error: error line 2 at position 45 invalid identifier 'IS_DYNAMIC'
```

Likely caused by #87

**Comment by joshelser** [comment]
Happened during v1.19 -> `main` upgrade of native app during finalize_setup.

The INTERNAL.PREDEFINED_LABELS table does not have the column is_dynamic, which makes me think internal.MIGRATE_PREDEFINED_LABELS_TABLE hasn't yet been called and something else is trying to use this column. Not sure what exactly, yet.

**Comment by joshelser** [comment]
failure trace is:

finalize_setup() -> refresh_queries(true) -> migrate_queries() -> migrate_view() -> update_label_view()

the tables are not updated until later in finalize_setup which is the problem.
